apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: {{ .Values.service.containerPort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
